data:
  train_dir: "data/train"
  test_dir: "data/test" 
  pred_dir: "data/pred"
  batch_size: 36
  # batch_size_for_sgd: 40
  img_size: 150

training:
  sgd_or_adamw: "adamw"

  learning_rate_sgd: 0.000375
  weight_decay_sgd: 0.003
  momentum_sgd: 0.93

  learning_rate_adamw: 0.000375
  betas0_adamw: 0.915
  betas1_adamw: 0.985
  weight_decay_adamw: 0.0017

  num_epochs: 42


model:
  num_classes: 6
