data:
  train_dir: "data/train"
  test_dir: "data/test" 
  pred_dir: "data/pred"
  batch_size: 36
  batch_size_old: 40
  img_size: 150

training:
  learning_rate: 0.0005
  weight_decay: 0.003
  momentum: 0.93
  num_epochs_sgd: 24
  num_epochs: 42


model:
  num_classes: 6
