data:
  train_dir: "data/train"
  test_dir: "data/test" 
  pred_dir: "data/pred"
  batch_size: 40
  img_size: 150

training:
  learning_rate: 0.000375
  beta0: 0.915
  beta1: 0.985
  weight_decay: 0.0017
  num_epochs: 30

model:
  num_classes: 6
